name: ant_media_flutter
description: Flutter Package to use Ant Media Server Enterprise Edition Streaming Engine on Android, iOS, Web and Desktop
version: 1.0.5
homepage: https://github.com/ant-media/WebRTC-Flutter-SDK

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.1
  collection: ^1.17.1
  flutter_webrtc: ^0.9.46
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.15
  shared_preferences_macos: ^2.0.4
  shared_preferences_web: ^2.0.4
  http: ^0.13.3
  path_provider: ^2.0.11
  path_provider_macos: ^2.0.6
  flutter_background: ^1.2.0
  record: ^5.0.1
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.ant_media_flutter
        pluginClass: AntMediaFlutterPlugin
      ios:
        pluginClass: AntMediaFlutterPlugin
